'use client';
import {useEffect,useState} from 'react';
const amount=(n:number)=>'$'+(n/100).toFixed(2);
async function api(path:string,input?:unknown){const r=await fetch('/api/checkout/'+path,{...(input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:{}),cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Please try again.');return data;}
export default function Checkout(){
 const [config,setConfig]=useState<any>(null),[bag,setBag]=useState<Record<string,number>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('guest'),[rates,setRates]=useState<any[]>([]),[rateToken,setRate]=useState(''),[order,setOrder]=useState<any>(null);
 const [details,setDetails]=useState({name:'',email:'',method:'pickup',createAccount:true,street1:'',street2:'',city:'',state:'AZ',zip:''});
 useEffect(()=>{try{setBag(JSON.parse(localStorage.getItem('cc-bag-v1')||'{}'));}catch{}api('config').then(setConfig).catch(e=>setError(e.message));},[]);
 function change(key:string,value:unknown){setDetails(d=>({...d,[key]:value}));setOrder(null);setRate('');setRates([]);}
 const items=Object.entries(bag).filter(([,q])=>Number.isInteger(q)&&q>0).map(([id,quantity])=>({id,quantity}));
 async function quote(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api('quote',{...details,items,rateToken,address:{...details,country:'US'}});if(result.rates)setRates(result.rates);else setOrder(result.order);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function pay(){setBusy(true);setError('');try{const result=await api('paypal',{orderId:order.id});if(result.url)window.location.assign(result.url);else window.location.assign('/checkout/return?order='+order.id);}catch(e){setError((e as Error).message);setBusy(false);}}
 function quantity(id:string,value:number){const next={...bag};if(value<=0)delete next[id];else next[id]=Math.min(value,20);setBag(next);localStorage.setItem('cc-bag-v1',JSON.stringify(next));setOrder(null);setRate('');setRates([]);}
 return <><p className="eyebrow">Your bag</p><h1>Checkout</h1><a href="/#shop">← Continue shopping</a>{config?.mode==='sandbox'&&<p className="message">Sandbox checkout · Test payments only. No real charge or fulfillment.</p>}{error&&<p role="alert" className="message">{error}</p>}{!config&&!error&&<p>Loading checkout…</p>}{config&&(!items.length?<p>Your bag is empty. <a href="/#shop">Shop cookies</a></p>:<>
 <section className="card" style={{marginTop:24}} aria-label="Bag items">{items.map(l=>{const p=config.products.find((p:any)=>p.id===l.id);return <div key={l.id} style={{borderBottom:'1px solid #F7E8CF',padding:'12px 0'}}><strong>{p?.title||'Unavailable product'}</strong><p>{p?`${amount(p.price_cents)} / ${p.package_count} per package`:''}</p><button type="button" onClick={()=>quantity(l.id,l.quantity-1)} aria-label={'Remove one '+p?.title}>−</button> <span>{l.quantity}</span> <button type="button" onClick={()=>quantity(l.id,l.quantity+1)} disabled={l.quantity>=20} aria-label={'Add one '+p?.title}>+</button></div>;})}</section>
 <div className="tabs" style={{marginTop:24}}><button aria-pressed={tab==='guest'} onClick={()=>setTab('guest')}>Guest</button><button aria-pressed={tab==='login'} onClick={()=>setTab('login')}>Login</button></div>
 {tab==='login'&&<p className="message"><a href="/account">Log in to your account</a>, then return to checkout. Your bag will be saved. You can also continue as a guest below.</p>}
 <form onSubmit={quote} className="card"><h2>Your details</h2><label htmlFor="name">Full name</label><input id="name" required autoComplete="name" value={details.name} onChange={e=>change('name',e.target.value)}/><label htmlFor="email">Email for your confirmation</label><input id="email" type="email" required autoComplete="email" value={details.email} onChange={e=>change('email',e.target.value)}/><label style={{display:'flex',gap:12,alignItems:'center'}}><input style={{width:20}} type="checkbox" checked={details.createAccount} onChange={e=>change('createAccount',e.target.checked)}/>Show account setup after checkout</label><p>You can finish your purchase without an account.</p>
 <h2>How would you like your order?</h2><label htmlFor="method">Pickup or shipping</label><select id="method" value={details.method} onChange={e=>change('method',e.target.value)} style={{font:'inherit',padding:12,width:'100%'}}>{config.pickupEnabled&&<option value="pickup">Pickup in Buckeye, Arizona · Free</option>}{config.shippingEnabled&&<option value="shipping">Shipping · calculated for your address</option>}</select>
 {details.method==='pickup'?<p>Pickup by appointment. Instructions are provided with your confirmed order.</p>:<>{(['street1','street2','city','state','zip'] as const).map(k=><div key={k}><label htmlFor={k}>{{street1:'Street address',street2:'Apartment / suite (optional)',city:'City',state:'State (2 letters)',zip:'ZIP code'}[k]}</label><input id={k} required={k!=='street2'} value={details[k]} onChange={e=>change(k,e.target.value)}/></div>)}{rates.length>0&&<><label htmlFor="rate">Shipping service</label><select id="rate" required value={rateToken} onChange={e=>{setRate(e.target.value);setOrder(null);}} style={{font:'inherit',padding:12,width:'100%'}}><option value="">Choose a service</option>{rates.map(r=><option key={r.id} value={r.token}>{r.provider} · {r.service} · {amount(r.amount_cents)}</option>)}</select></>}</>}
 <button disabled={busy} type="submit">{busy?'Please wait…':details.method==='shipping'&&!rateToken?'Get shipping rates':'Review total'}</button></form>
 {order&&<section className="card" style={{marginTop:24}}><h2>Your order total</h2><p>Cookies & treats: {amount(order.subtotal_cents)}</p><p>Shipping: {amount(order.shipping_cents)}</p><p>Tax: {amount(order.tax_cents)}</p><h2>Total {amount(order.total_cents)}</h2><button onClick={pay} disabled={busy}>{busy?'Connecting…':order.mode==='sandbox'?'Continue to PayPal Sandbox':'Pay with PayPal'}</button><p>You’ll review and approve payment securely with PayPal.</p></section>}
 </>)}</>;
}
