'use client';
import {useEffect,useState} from 'react';
const amount=(n:number)=>'$'+(n/100).toFixed(2);
async function api(path:string,input?:unknown){const r=await fetch('/api/checkout/'+path,{...(input?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)}:{}),cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'Please try again.');return data;}
export default function Checkout(){
 const [config,setConfig]=useState<any>(null),[bag,setBag]=useState<Record<string,number>>({}),[error,setError]=useState(''),[busy,setBusy]=useState(false),[savingBag,setSavingBag]=useState(false),[tab,setTab]=useState('guest'),[rates,setRates]=useState<any[]>([]),[rateToken,setRate]=useState(''),[order,setOrder]=useState<any>(null),[acceptedTerms,setAcceptedTerms]=useState(false);
 const [addresses,setAddresses]=useState<any[]>([]),[account,setAccount]=useState<any>(undefined);
 const [details,setDetails]=useState({name:'',email:'',discountCode:'',method:'pickup',createAccount:true,street1:'',street2:'',city:'',state:'AZ',zip:''});
 useEffect(()=>{api('config').then(setConfig).catch(e=>setError(e.message));fetch('/api/cart',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setBag(Object.fromEntries(d.items.map((i:any)=>[i.id,i.quantity])));}).catch(e=>setError(e.message));fetch('/api/account',{cache:'no-store'}).then(async r=>{if(r.status===401)return null;const d=await r.json();if(!r.ok)throw Error(d.error||'Could not check your account. Please reload checkout.');return d;}).then(d=>{setAccount(d);if(d){const saved=d.addresses?.length===1?d.addresses[0].address:null;setDetails(v=>({...v,name:v.name||d.name||'',email:d.email,createAccount:false,...(saved?{street1:saved.street1||'',street2:saved.street2||'',city:saved.city||'',state:saved.state||'AZ',zip:saved.zip||''}:{})}));setAddresses(d.addresses||[]);}}).catch(e=>setError(e.message));},[]);
 function change(key:string,value:unknown){setAcceptedTerms(false);setDetails(d=>({...d,[key]:value}));setOrder(null);setRate('');setRates([]);}
 const items=Object.entries(bag).filter(([,q])=>Number.isInteger(q)&&q>0).map(([id,quantity])=>({id,quantity}));
 async function quote(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await api('quote',{...details,items,rateToken,address:{...details,country:'US'}});if(result.rates)setRates(result.rates);else {setOrder(result.order);setAcceptedTerms(false);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function pay(){setBusy(true);setError('');try{const result=await api('paypal',{orderId:order.id,acceptedTerms,termsVersion:config.agreement.version});if(result.url)window.location.assign(result.url);else window.location.assign('/checkout/return?order='+order.id);}catch(e){setError((e as Error).message);setBusy(false);}}
 async function quantity(id:string,value:number){if(savingBag)return;const next={...bag};if(value<=0)delete next[id];else next[id]=Math.min(value,20);setAcceptedTerms(false);setSavingBag(true);setError('');setOrder(null);setRate('');setRates([]);try{const r=await fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:Object.entries(next).map(([id,quantity])=>({id,quantity}))})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save bag.');setBag(next);}catch(e){setError((e as Error).message);}finally{setSavingBag(false);}}

 return <div className="checkout-page"><p className="eyebrow">Your bag</p><h1>Checkout</h1><a href="/#shop">← Continue shopping</a>{config?.mode==='sandbox'&&<p className="message">Sandbox checkout · Test payments only. No real charge or fulfillment.</p>}{error&&<p role="alert" className="message">{error}</p>}{!config&&!error&&<p>Loading checkout…</p>}{config&&(!items.length?<p>Your bag is empty. <a href="/#shop">Shop cookies</a></p>:<>
 <ol className="checkout-steps" aria-label="Checkout steps"><li>1. Enter your details</li><li>2. Review your order</li><li>3. Delivery & payment</li></ol><form onSubmit={quote} className="checkout-columns"><div className="checkout-details">
 {account===undefined?<p role="status">Checking your account…</p>:account?<div className="checkout-account"><span><strong>Signed in</strong><br/>{account.email}</span><a href="/account">Manage account</a></div>:<div className="tabs" style={{marginTop:24}}><button type="button" disabled={busy} aria-pressed={tab==='guest'} onClick={()=>setTab('guest')}>Guest</button><button type="button" disabled={busy} aria-pressed={tab==='login'} onClick={()=>setTab('login')}>Login</button></div>}
 {account===null&&tab==='login'&&<p className="message"><a href="/account">Log in to your account</a>, then return to checkout. Your bag will be saved. You can also continue as a guest below.</p>}
 <section className="card"><h2>1. Your details</h2><label htmlFor="name">Full name</label><input disabled={busy} id="name" required autoComplete="name" value={details.name} onChange={e=>change('name',e.target.value)}/><label htmlFor="email">Email for your confirmation</label><input disabled={busy} id="email" type="email" required readOnly={!!account} autoComplete="email" value={details.email} onChange={e=>change('email',e.target.value)}/>{account===null&&<><label style={{display:'flex',gap:12,alignItems:'center'}}><input disabled={busy} style={{width:20}} type="checkbox" checked={details.createAccount} onChange={e=>change('createAccount',e.target.checked)}/>Show account setup after checkout</label><p>You can finish your purchase without an account.</p></>}
</section>
</div><aside className="card checkout-summary" aria-label="Order summary"> <section aria-label="Bag items"><h2>2. Your order</h2>{items.map(l=>{const p=config.products.find((p:any)=>p.id===l.id);return <div key={l.id} className="checkout-item"><div><strong>{p?.title||'Unavailable product'}</strong><p>{p?`${amount(p.price_cents)} / ${p.package_count} per package`:''}</p></div><label className="checkout-quantity">Qty<select disabled={savingBag||busy} value={l.quantity} aria-label={'Quantity for '+(p?.title||'product')} onChange={e=>quantity(l.id,Number(e.target.value))}><option value={0}>Remove</option>{Array.from({length:20},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label></div>;})}</section><div className="checkout-subtotal"><span>Subtotal</span><strong>{amount(items.reduce((sum,l)=>sum+(config.products.find((p:any)=>p.id===l.id)?.price_cents||0)*l.quantity,0))}</strong></div> <section className="checkout-fulfillment"><h2>3. Delivery & discount</h2><label htmlFor="method">Fulfillment method</label><select disabled={busy} id="method" value={details.method} onChange={e=>change('method',e.target.value)} style={{font:'inherit',padding:12,width:'100%'}}>{config.pickupEnabled&&<option value="pickup">Pickup in Buckeye, Arizona · Free</option>}{(config.deliveryEnabled||config.shippingEnabled)&&<option value="shipping">Deliver to my address</option>}</select>
 {details.method!=='pickup'&&<p>{config.deliveryEnabled?'Free local delivery within approximately 10 miles. Otherwise, shipping is calculated using this same address.':'Shipping is calculated using your address.'}</p>}{details.method==='pickup'?<p>Pickup by appointment. Instructions are provided with your confirmed order.</p>:<>{addresses.length>0&&<label>Use a saved address<select disabled={busy} defaultValue="" onChange={e=>{const a=addresses.find(a=>a.id===e.target.value)?.address;if(a){setAcceptedTerms(false);setDetails(d=>({...d,street1:a.street1||'',street2:a.street2||'',city:a.city||'',state:a.state||'',zip:a.zip||''}));setOrder(null);setRate('');setRates([]);}}}><option value="">Choose saved address</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.address.street1}, {a.address.city}</option>)}</select></label>}{(['street1','street2','city','state','zip'] as const).map(k=><div key={k}><label htmlFor={k}>{{street1:'Street address',street2:'Apartment / suite (optional)',city:'City',state:'State (2 letters)',zip:'ZIP code'}[k]}</label><input disabled={busy} id={k} required={k!=='street2'} value={details[k]} onChange={e=>change(k,e.target.value)}/></div>)}{details.method==='shipping'&&rates.length>0&&<><label htmlFor="rate">Shipping service</label><select disabled={busy} id="rate" required value={rateToken} onChange={e=>{setRate(e.target.value);setOrder(null);}} style={{font:'inherit',padding:12,width:'100%'}}><option value="">Choose a service</option>{rates.map(r=><option key={r.id} value={r.token}>{r.provider} · {r.service} · {amount(r.amount_cents)}</option>)}</select></>}</>}
 <label htmlFor="discount">Discount code (optional)</label><input disabled={busy} id="discount" value={details.discountCode} onChange={e=>change('discountCode',e.target.value)}/><button disabled={busy||savingBag||account===undefined} type="submit">{busy?'Please wait…':details.method==='shipping'&&!rateToken?'Check delivery & total':'Review total'}</button></section>{!order&&<p className="checkout-estimate">Tax, shipping, and any discount are confirmed when you review your total.</p>} {order&&<section className="checkout-totals" aria-live="polite"><h2>Your order total</h2><p>Cookies & treats (including applied discount): {amount(order.subtotal_cents)}</p><p>{order.fulfillment.method==='pickup'?'Pickup':order.fulfillment.method==='delivery'?'Local delivery':'Shipping'}: {order.shipping_cents===0?'Free':amount(order.shipping_cents)}</p><p>Tax: {amount(order.tax_cents)}</p><h2>Total {amount(order.total_cents)}</h2><h3>Terms & Conditions of Sale</h3><div className="sale-terms" tabIndex={0}>{config.agreement.text}</div><label className="checkbox-label"><input disabled={busy} type="checkbox" checked={acceptedTerms} onChange={e=>setAcceptedTerms(e.target.checked)}/>I have read and agree to the Terms & Conditions of Sale, including the potential-allergen and freshness information.</label><button type="button" onClick={pay} disabled={busy||!acceptedTerms}>{busy?'Connecting…':'Continue to payment'}</button><p>You’ll review and approve payment securely with PayPal.</p></section>}
 </aside></form></>)}</div>;
}
