import {body,db,failure,sameOrigin} from '@/lib/checkout/server';
import {admin,audit,publicSite} from '@/lib/management/auth';
import {salePrice,productDetails,socials} from '@/lib/management/validation';
import {CheckoutError,text,email} from '@/lib/checkout/core';
import {notifyOrder} from '@/lib/checkout/complete';
import {randomUUID} from 'node:crypto';
export async function GET(){try{await admin();const [{data:products,error},{data:orders},{data:reviews},{data:subscribers},{data:discounts},site]=await Promise.all([db().from('commerce_products').select('*').order('id'),db().from('commerce_orders').select('id,created_at,customer_name,email,status,mode,items,total_cents,fulfillment').order('created_at',{ascending:false}).limit(100),db().from('commerce_reviews').select('*').order('created_at',{ascending:false}).limit(100),db().from('commerce_newsletter').select('email,status,confirmed_at').order('requested_at',{ascending:false}).limit(500),db().from('commerce_discounts').select('*'),publicSite()]);if(error)throw error;return Response.json({products,orders:orders||[],reviews:reviews||[],subscribers:subscribers||[],discounts:discounts||[],site},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(r:Request){try{sameOrigin(r);const user=await admin();
 if(r.headers.get('content-type')?.startsWith('multipart/form-data')){
 const form=await r.formData();const file=form.get('image');if(!(file instanceof File)||file.size>5*1024*1024)throw new CheckoutError('Choose an image under 5 MB.');
 const bytes=Buffer.from(await file.arrayBuffer());const png=bytes.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const webp=bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';const type=png?'image/png':jpg?'image/jpeg':webp?'image/webp':null;if(!type||file.type!==type)throw new CheckoutError('Upload a PNG, JPEG, or WebP image.');
 const path=randomUUID()+'.'+(png?'png':jpg?'jpg':'webp');const {error}=await db().storage.from('product-images').upload(path,bytes,{contentType:type,upsert:false});if(error)throw error;await audit(user.id,'image-upload',path);return Response.json({url:db().storage.from('product-images').getPublicUrl(path).data.publicUrl});}
 const input=await body(r);
 if(input.action==='product'){
 const p=input.product;if(p.product_type!=='human-cookie'&&p.product_type!=='dog-treat'&&(!Number.isInteger(p.package_count)||p.package_count<1||p.package_count>100))throw new CheckoutError('Enter a valid package count.');const base=Number(p.base_cents),markup=Number(p.markup_value);const details=productDetails(p.details);const record={title:text(p.title,1,100),slug:text(p.slug,1,100),base_cents:base,markup_type:p.markup_type,markup_value:markup,price_cents:salePrice(base,p.markup_type,markup),package_count:p.product_type==='dog-treat'?10:p.product_type==='human-cookie'?12:p.package_count,product_type:text(p.product_type,1,50),active:p.active===true,details};
 if(!/^[a-z0-9-]+$/.test(record.slug))throw new CheckoutError('Use letters, numbers, and hyphens for the product URL name.');if(p.id){const {data:original,error:originalError}=await db().from('commerce_products').select('details').eq('id',p.id).single();if(originalError)throw originalError;record.details.defaultImage=original.details.defaultImage||'/brand/logo.png';}const query=p.id?db().from('commerce_products').update(record).eq('id',p.id):db().from('commerce_products').insert(record);const {error}=await query;if(error)throw error;await audit(user.id,'product-save',p.id);
 }else if(input.action==='bulk-price'){
 if(!Array.isArray(input.ids)||!input.ids.length||input.ids.length>100)throw new CheckoutError('Select products.');const {data,error}=await db().from('commerce_products').select('id,base_cents').in('id',input.ids);if(error)throw error;const updates=(data||[]).map(p=>({...p,markup_type:input.kind,markup_value:input.value,price_cents:salePrice(p.base_cents,input.kind,input.value)}));const {error:bulkError}=await db().rpc('set_commerce_markup',{p_ids:input.ids,p_kind:input.kind,p_value:input.value});if(bulkError)throw bulkError;await audit(user.id,'bulk-price',input.ids.join(','));
 }else if(input.action==='site'){
 const old=await publicSite(),s=input.site;const next={...old,contactEmail:email(s.contactEmail),socials:socials(s.socials),monthlyProductId:text(s.monthlyProductId,1,100),storyIntro:text(s.storyIntro,1,1500),storyBody:text(s.storyBody,1,10000),cancellationPolicy:text(s.cancellationPolicy,1,3000),allergenNotice:text(s.allergenNotice,1,3000)};const {error}=await db().from('commerce_settings').update({value:next}).eq('key','public_site');if(error)throw error;await audit(user.id,'site-save');
 }else if(input.action==='discount'){const d=input.discount;const code=text(d.code,3,40).toUpperCase();if(!/^[A-Z0-9_-]+$/.test(code)||!Number.isInteger(d.percent)||d.percent<1||d.percent>90||!Number.isSafeInteger(d.minimum_cents)||d.minimum_cents<0)throw new CheckoutError('Check the discount code, percent (1–90), and minimum.');const {error}=await db().from('commerce_discounts').upsert({code,percent:d.percent,minimum_cents:d.minimum_cents,active:d.active===true});if(error)throw error;await audit(user.id,'discount-save',code);
 }else if(input.action==='review'){
 if(!['approved','rejected'].includes(input.status))throw new CheckoutError('Choose approve or reject.');const {error}=await db().from('commerce_reviews').update({status:input.status}).eq('id',input.id);if(error)throw error;await audit(user.id,'review-'+input.status,input.id);
 }else if(input.action==='resend-order'){
 const {data,error}=await db().from('commerce_orders').select('*').eq('id',input.id).eq('status','paid').single();if(error)throw error;if(!await notifyOrder(data))throw new CheckoutError('Delivery is pending or requires manual reconciliation.',503);await audit(user.id,'order-email-retry',input.id);
 }else throw new CheckoutError('Unknown action.');
 return Response.json({saved:true});}catch(e){return failure(e);}}
