import {CheckoutError,text} from '../checkout/core';
export const nutrients=[['calories','Calories',1008,'kcal'],['fat','Total Fat',1004,'g'],['saturated','Saturated Fat',1258,'g'],['trans','Trans Fat',1257,'g'],['cholesterol','Cholesterol',1253,'mg'],['sodium','Sodium',1093,'mg'],['carbs','Total Carbohydrate',1005,'g'],['fiber','Dietary Fiber',1079,'g'],['sugars','Total Sugars',2000,'g'],['addedSugar','Added Sugars',1235,'g'],['protein','Protein',1003,'g'],['vitaminD','Vitamin D',1114,'µg'],['calcium','Calcium',1087,'mg'],['iron','Iron',1089,'mg'],['potassium','Potassium',1092,'mg']] as const;
import {allergens} from './constants';
export {allergens} from './constants';
const patterns=[/\b(milk|butter|cream|whey|casein|cheese|yogurt)\b/i,/\beggs?\b/i,/\b(wheat|all.purpose flour|semolina|durum)\b/i,/\b(soy|soya|soybean)\b/i,/\bpeanuts?\b/i,/\b(almond|walnut|pecan|macadamia|cashew|pistachio|hazelnut|brazil nut)s?\b/i,/\b(sesame|tahini)\b/i,/\b(fish|salmon|tuna|cod|anchovy)\b/i,/\b(shrimp|prawn|lobster|crab|crayfish)\b/i];
export function suggestAllergens(value:string){return allergens.filter((_,i)=>patterns[i].test(value));}
export function grams(row:any){const amount=Number(row.amount);const factor:Record<string,number>={g:1,kg:1000,oz:28.349523125,lb:453.59237};const f=factor[row.unit]??Number(row.gramsPerUnit);if(!Number.isFinite(amount)||amount<=0||!Number.isFinite(f)||f<=0||amount*f>1000000)throw new CheckoutError('Every ingredient needs a positive amount and a verified gram conversion.');return amount*f;}
export function recipeInput(input:any){if(!input||!Array.isArray(input.rows)||!input.rows.length||input.rows.length>50)throw new CheckoutError('Add between 1 and 50 ingredient rows.');const yieldCount=Number(input.yieldCount),servingGrams=Number(input.servingGrams);if(!Number.isInteger(yieldCount)||yieldCount<1||yieldCount>10000||!Number.isFinite(servingGrams)||servingGrams<=0||servingGrams>5000)throw new CheckoutError('Enter the number of finished cookies and the measured baked weight of one cookie.');return {instructions:text(input.instructions||'',0,10000),yieldCount,servingGrams,reviewed:input.reviewed===true,crossContact:text(input.crossContact||'',0,1000),confirmedAllergens:allergens.filter(a=>input.confirmedAllergens?.includes(a)),rows:input.rows.map((r:any)=>{if(!Number.isSafeInteger(r.fdcId)||r.fdcId<1||!['g','kg','oz','lb','cup','tbsp','tsp','each'].includes(r.unit))throw new CheckoutError('Choose a USDA food and a unit for every ingredient.');return {fdcId:r.fdcId,name:text(r.name,1,200),amount:Number(r.amount),unit:r.unit,gramsPerUnit:Number(r.gramsPerUnit)||0,grams:grams(r)};})};}
export function calculateRecipe(recipe:ReturnType<typeof recipeInput>,foods:any[],packageCount:number){
 const values:Record<string,number|null>={};const missing:string[]=[];
 for(const [key,label,id,unit] of nutrients){let total=0,complete=true;recipe.rows.forEach((row:any)=>{const food=foods.find(f=>f.fdcId===row.fdcId);const options=key==='calories'?[1008,2048,2047]:key==='sugars'?[2000,1063]:[id];const item=options.map(n=>food?.foodNutrients?.find((v:any)=>v.nutrient?.id===n&&Number.isFinite(v.amount))).find(Boolean);const sourceUnit=String(item?.nutrient?.unitName||'').toLowerCase().replace('ug','µg');if(!item||sourceUnit!==unit.toLowerCase()||item.amount<0)complete=false;else total+=item.amount*row.grams/100;});values[key]=complete?Math.round(total/recipe.yieldCount*100)/100:null;if(!complete)missing.push(label);}
 const labels=recipe.rows.map((r:any)=>{const f=foods.find(f=>f.fdcId===r.fdcId);return {grams:r.grams,name:r.name,label:r.name+(f?.ingredients?' ('+String(f.ingredients).slice(0,4000)+')':''),source:f?.description||''};});
 const suggested=suggestAllergens(labels.map((l:any)=>l.label+' '+l.source).join(' '));
 return {servingGrams:recipe.servingGrams,servingsPerContainer:packageCount,values,missing,ingredients:labels.sort((a:any,b:any)=>b.grams-a.grams).map((l:any)=>l.name).join(', '),allergens:Array.from(new Set([...suggested,...recipe.confirmedAllergens])).join(', '),crossContact:recipe.crossContact,suggestedAllergens:suggested,estimated:true,calculatedAt:new Date().toISOString()};
}

export function recipeDraft(input:any){
 if(!input||!Array.isArray(input.rows)||input.rows.length>50)throw new CheckoutError('Use up to 50 USDA ingredients.');
 const numeric=(v:unknown,max:number)=>{const n=Number(v)||0;if(!Number.isFinite(n)||n<0||n>max)throw new CheckoutError('Check recipe amounts and serving sizes.');return n;};
 return {instructions:text(input.instructions||'',0,10000),yieldCount:numeric(input.yieldCount,10000),servingGrams:numeric(input.servingGrams,5000),reviewed:false,crossContact:text(input.crossContact||'',0,1000),confirmedAllergens:allergens.filter(a=>input.confirmedAllergens?.includes(a)),rows:input.rows.map((r:any)=>{if(!Number.isSafeInteger(r.fdcId)||r.fdcId<1||!['g','kg','oz','lb','cup','tbsp','tsp','each'].includes(r.unit))throw new CheckoutError('Choose a USDA ingredient and unit.');return {fdcId:r.fdcId,name:text(r.name,1,200),amount:numeric(r.amount,1000000),unit:r.unit,gramsPerUnit:numeric(r.gramsPerUnit,1000000)};})};
}
