'use client';
import {useEffect,useRef,useState} from 'react';
const money=(n:number)=>'$'+(n/100).toFixed(2);
export default function PaymentReturn(){
 const [result,setResult]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(true),started=useRef(false);
 async function confirm(){setBusy(true);setError('');try{const orderId=new URLSearchParams(window.location.search).get('order');const r=await fetch('/api/checkout/capture',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({orderId})});const data=await r.json();if(!r.ok)throw new Error(data.error);if(data.status!=='paid')throw new Error('Payment is still being verified.');setResult(data);localStorage.removeItem('cc-bag-v1');}catch(e){setError((e as Error).message||'Please check your payment again.');}finally{setBusy(false);}}
 useEffect(()=>{if(!started.current){started.current=true;void confirm();}},[]);
 const a=result?.fulfillment.address;
 return <section className="card" aria-live="polite"><h1>{result?'Thank you for your order!':'Confirming your payment…'}</h1>{result?<><p>{result.mode==='sandbox'?'Sandbox test completed — no real charge or fulfillment.':'Your payment is confirmed and your order is saved.'}</p><p>Order: {result.id}</p><h2>Your receipt</h2>{result.items.map((l:any)=><p key={l.id}>{l.quantity} × {l.title} ({l.package_count} per package) — {money(l.quantity*l.unit_cents)}</p>)}<p>Subtotal: {money(result.subtotal_cents)}</p>{!!result.donation_cents&&<p>CureSearch support: {money(result.donation_cents)}</p>}<p>Shipping: {money(result.shipping_cents)}</p><p>Sales tax: {money(result.tax_cents)}</p><h2>Total paid {money(result.total_cents)}</h2><h3>{result.fulfillment.method==='pickup'?'Pickup details':result.fulfillment.method==='delivery'?'Local delivery details':'Shipping details'}</h3><p>{a.name}<br/>{a.street1}{a.street2&&<><br/>{a.street2}</>}<br/>{a.city}, {a.state} {a.zip}</p><p>{result.fulfillment.method==='pickup'?'Pickup is by appointment. We will contact you when your order is ready.':result.fulfillment.method==='delivery'?'We will contact you to arrange local delivery.':'We will send shipping details when your order is dispatched.'}</p><p>{result.emailSent?'Your confirmation email has been sent.':'Your payment is saved. Your confirmation email is pending delivery.'}</p>{result.createAccount&&<p><a className="button" href="/account">Set up your account</a></p>}<a href="/#shop">Continue shopping</a></>:<>{busy&&<p role="status">Please wait while we verify payment and save your order.</p>}{error&&<><p role="alert" className="message">{error} Do not place a second order while this is being checked.</p><button onClick={confirm} disabled={busy}>Check payment status again</button></>}</>}</section>;
}
