import {normalizeState} from '../us-states';
import {createHash} from 'node:crypto';
import {CheckoutError} from './errors';
export {CheckoutError} from './errors';
export type Address={name:string;street1:string;street2?:string;city:string;state:string;zip:string;country:'US';phone?:string};
export type Product={id:string;title:string;price_cents:number;package_count:number;product_type:string;tax_code?:string;active:boolean};
export type Line={id:string;title:string;quantity:number;unit_cents:number;package_count:number;product_type:string;tax_code?:string};
export const money=(cents:number)=>(cents/100).toFixed(2);
export function cents(value:unknown){const s=String(value);if(!/^\d+(\.\d{1,2})?$/.test(s))throw new CheckoutError('Invalid provider amount.',502);const [whole,fraction='']=s.split('.');const amount=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(amount))throw new CheckoutError('Invalid provider amount.',502);return amount;}
export function text(value:unknown,min:number,max:number){if(typeof value!=='string'||value.trim().length<min||value.trim().length>max)throw new CheckoutError('Please check the checkout details.');return value.trim();}
export function email(value:unknown){const e=text(value,3,254).toLowerCase();if(!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(e))throw new CheckoutError('Enter a valid email address.');return e;}
export function address(value:unknown):Address{if(!value||typeof value!=='object')throw new CheckoutError('Enter a delivery address.');const v=value as Record<string,unknown>;const state=normalizeState(v.state),zip=text(v.zip,5,10);if(!/^[A-Z]{2}$/.test(state)||!/^\d{5}(-\d{4})?$/.test(zip)||v.country!=='US')throw new CheckoutError('Enter a valid US address.');return {name:text(v.name,1,100),street1:text(v.street1,3,150),street2:typeof v.street2==='string'?v.street2.trim().slice(0,100):'',city:text(v.city,1,80),state,zip,country:'US',...(typeof v.phone==='string'&&v.phone.trim()?{phone:text(v.phone,7,30)}:{})};}
export function cart(value:unknown):{id:string;quantity:number}[]{if(!Array.isArray(value)||!value.length||value.length>20)throw new CheckoutError('Add a product to your bag.');const ids=new Set();return value.map(v=>{if(!v||typeof v.id!=='string'||v.id.length>100||ids.has(v.id)||!Number.isInteger(v.quantity)||v.quantity<1||v.quantity>20)throw new CheckoutError('Check the quantities in your bag (maximum 20 packages per product).');ids.add(v.id);return {id:v.id,quantity:v.quantity};});}
export function priceCart(input:unknown,products:Product[]):Line[]{return cart(input).map(({id,quantity})=>{const p=products.find(p=>p.id===id&&p.active);if(!p)throw new CheckoutError('A product in your bag is no longer available.');if(!Number.isSafeInteger(p.price_cents)||p.price_cents<=0)throw new CheckoutError('A product price is unavailable.',503);return {id,title:p.title,quantity,unit_cents:p.price_cents,package_count:p.package_count,product_type:p.product_type,...(p.tax_code?{tax_code:p.tax_code}:{})};});}
export const subtotal=(lines:Line[])=>lines.reduce((n,l)=>n+l.unit_cents*l.quantity,0);
export const digest=(value:unknown)=>createHash('sha256').update(JSON.stringify(value)).digest('hex');
export function parcels(lines:Line[]){if(lines.some(l=>l.product_type!=='human-cookie'))throw new CheckoutError('Shipping for this assortment is not configured. Please choose pickup.');let count=lines.reduce((n,l)=>n+l.quantity*l.package_count,0);if(count>240)throw new CheckoutError('Please contact us to arrange shipping for this large order.');const result=[];while(count>0){const units=Math.min(count,36);const preset=units<=12?[9,6,3,8]:units<=24?[12,9,4,12]:[12,12,5,16];result.push({length:String(preset[0]),width:String(preset[1]),height:String(preset[2]),distance_unit:'in',weight:String(units*2+preset[3]),mass_unit:'oz'});count-=units;}return result;}

export function captureEvidence(result:any,o:{id:string;paypal_order_id:string|null;total_cents:number}){if(result.id!==o.paypal_order_id||result.status!=='COMPLETED'||!Array.isArray(result.purchase_units)||result.purchase_units.length!==1)throw new CheckoutError('Payment is not completed yet. Please check again.',409);const unit=result.purchase_units[0];if(unit.reference_id!==o.id||unit.custom_id!==o.id||unit.amount?.currency_code!=='USD'||cents(unit.amount.value)!==o.total_cents)throw new CheckoutError('Payment needs manual review. Do not pay again.',409);const captures=unit.payments?.captures;if(!Array.isArray(captures)||captures.length!==1||captures[0].status!=='COMPLETED'||captures[0].amount?.currency_code!=='USD'||cents(captures[0].amount.value)!==o.total_cents||!captures[0].id)throw new CheckoutError('Payment needs manual review. Do not pay again.',409);return {id:String(captures[0].id),total:cents(captures[0].amount.value)};}
