import 'server-only';
import {createClient} from '@supabase/supabase-js';
import {cookies} from 'next/headers';
import {createHash,randomBytes} from 'node:crypto';
import {SUPABASE_URL} from '@/lib/auth-config';
import {CheckoutError,address,type Address,type Line} from './core';
export type Settings={enabled:boolean;paymentMode:'sandbox'|'live';origin:Address;pickupEnabled:boolean;shippingEnabled:boolean;shippingMode:'sandbox'|'live'};
export type Order={id:string;status:string;mode:'sandbox'|'live';session_hash:string;customer_id:string|null;email:string;customer_name:string;create_account:boolean;items:Line[];fulfillment:{method:'pickup'|'shipping';address:Address;rate?:{id:string;provider:string;service:string;amount_cents:number};mode?:string};tax_details:Record<string,unknown>;subtotal_cents:number;shipping_cents:number;tax_cents:number;total_cents:number;currency:'USD';paypal_order_id:string|null;expires_at:string;paid_at:string|null;paypal_capture_id:string|null};
export function db(){const key=process.env.SUPABASE_SECRET_KEY;if(!key)throw new CheckoutError('Checkout is still being configured.',503);return createClient(SUPABASE_URL,key,{auth:{persistSession:false,autoRefreshToken:false}});}
export async function settings(){const {data,error}=await db().from('commerce_settings').select('value').eq('key','checkout').single();if(error||!data)throw new CheckoutError('Checkout is still being configured.',503);const s=data.value as Settings;if(!s.enabled)throw new CheckoutError('Online ordering is not enabled yet.',503);if(!['sandbox','live'].includes(s.paymentMode)||s.paymentMode!==process.env.PAYPAL_ENVIRONMENT)throw new CheckoutError('Payment configuration needs attention.',503);if(!process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID||!process.env.PAYPAL_CLIENT_SECRET)throw new CheckoutError('Payment configuration needs attention.',503);s.origin=address(s.origin);return s;}
export async function session(create=false){const jar=await cookies();let value=jar.get('cc_checkout')?.value;if(!value&&create){value=randomBytes(32).toString('hex');jar.set('cc_checkout',value,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:60*60*24*7});}if(!value||!/^[a-f0-9]{64}$/.test(value))throw new CheckoutError('Please reload checkout and try again.',401);return createHash('sha256').update(value).digest('hex');}
export async function ownedOrder(id:unknown){if(typeof id!=='string'||!/^[a-f0-9-]{36}$/.test(id))throw new CheckoutError('Order not found.',404);const hash=await session();const {data,error}=await db().from('commerce_orders').select('*').eq('id',id).eq('session_hash',hash).single();if(error||!data)throw new CheckoutError('Order not found in this checkout session.',404);return data as Order;}
export function sameOrigin(request:Request){if(request.headers.get('origin')!==new URL(request.url).origin)throw new CheckoutError('Request not allowed.',403);}
export async function body(request:Request){sameOrigin(request);if(!request.headers.get('content-type')?.startsWith('application/json'))throw new CheckoutError('Invalid request.',415);const raw=await request.text();if(raw.length>20000)throw new CheckoutError('Request too large.',413);try{return JSON.parse(raw);}catch{throw new CheckoutError('Invalid request.');}}
export function failure(error:unknown){const known=error instanceof CheckoutError;return Response.json({error:known?error.message:'We could not complete that request. Please try again.'},{status:known?error.status:503,headers:{'Cache-Control':'no-store'}});}
