import {publicSite} from '@/lib/management/auth';
import {saleAgreement,requireAgreement} from '@/lib/checkout/terms';
import {body,settings,ownedOrder,db,failure} from '@/lib/checkout/server';
import {CheckoutError} from '@/lib/checkout/core';
import {paypal,paymentBody} from '@/lib/checkout/providers';
export async function POST(request:Request){try{const input=await body(request),s=await settings(),order=await ownedOrder(input.orderId);if(order.mode!==s.paymentMode)throw new CheckoutError('Payment settings changed. Please review checkout again.',409);if(order.status==='paid')return Response.json({paid:true,orderId:order.id});if(!['quoted','awaiting_payment'].includes(order.status))throw new CheckoutError('This order cannot be paid.',409);if(Date.parse(order.expires_at)<Date.now()&&!order.paypal_order_id)throw new CheckoutError('Your total expired. Please review checkout again.',409);
 const agreement=saleAgreement(await publicSite());requireAgreement(input.acceptedTerms,input.termsVersion,agreement);if(!order.paypal_order_id){const {error:acceptError}=await db().from('commerce_orders').update({tax_details:{...order.tax_details,saleAgreement:{...agreement,acceptedAt:new Date().toISOString(),email:order.email,customerId:order.customer_id}}}).eq('id',order.id).eq('session_hash',order.session_hash);if(acceptError)throw acceptError;}else if(!(order.tax_details as any).saleAgreement)throw new CheckoutError('Please review a new order total and accept the sale agreement.',409);
 const result=order.paypal_order_id?await paypal('/v2/checkout/orders/'+order.paypal_order_id,order.mode):await paypal('/v2/checkout/orders',order.mode,'POST',paymentBody(order,new URL(request.url).origin),order.id);
 const {error}=await db().from('commerce_orders').update({paypal_order_id:result.id,status:'awaiting_payment'}).eq('id',order.id).in('status',['quoted','awaiting_payment']);if(error)throw error;
 const link=result.links?.find((l:any)=>l.rel==='payer-action'||l.rel==='approve')?.href;if(!link){if(result.status==='APPROVED'||result.status==='COMPLETED')return Response.json({approved:true,orderId:order.id});throw new CheckoutError('PayPal approval is unavailable. Please try again.',502);}const url=new URL(link);if(url.protocol!=='https:'||!['www.paypal.com','www.sandbox.paypal.com','paypal.com','sandbox.paypal.com'].includes(url.hostname))throw new CheckoutError('Invalid payment destination.',502);return Response.json({url:link});}catch(error){return failure(error);}}
