import type { Metadata } from 'next';
import Link from 'next/link';
import {ProfileIcon} from '@/components/profile-icon';
import '@fontsource/inter/400.css';
import '@fontsource/inter/600.css';
import '@fontsource/dm-serif-display/400.css';
import './globals.css';
export const metadata:Metadata={title:'Cookies & Chips',description:'Baked with love.',robots:{index:false,follow:false}};
export default function Layout({children}:{children:React.ReactNode}) {return <html lang="en"><body><div className="ribbon">Good cookies make a brighter day. · Baked with love in Arizona.</div><header><Link href="/" aria-label="Cookies and Chips home"><img src="/brand/logo.png" alt="Cookies & Chips — Baked with Love" width="96" height="96" /></Link><nav className="desktop-nav" aria-label="Main navigation"><Link href="/">Home</Link><Link href="/#shop">Shop</Link><Link href="/my-story">My Story</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link></nav><details className="mobile-nav"><summary>Menu</summary><nav aria-label="Mobile navigation"><Link href="/">Home</Link><Link href="/#shop">Shop</Link><Link href="/my-story">My Story</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link></nav></details><div className="header-actions"><ProfileIcon/><Link href="/checkout" aria-label="Shopping bag" title="Shopping bag"><svg viewBox="0 0 24 24" width="23" height="23" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M5 7h14l1 14H4L5 7Z"/><path d="M9 8V6a3 3 0 0 1 6 0v2"/></svg></Link></div></header><main>{children}</main><footer className="site-footer"><Link href="/" aria-label="Cookies and Chips home"><img src="/brand/logo.png" width="96" height="96" alt="Cookies & Chips"/></Link><nav aria-label="Footer navigation"><Link href="/#shop">Shop cookies</Link><Link href="/my-story">My Story</Link><Link href="/shipping">Shipping & pickup</Link><Link href="/faq">FAQ</Link><Link href="/contact">Contact</Link><Link href="/policies">Policies & allergens</Link></nav><p>Baked with love in Arizona.</p></footer></body></html>}
