import 'server-only';
import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {db} from '@/lib/checkout/server';
import {validateParcel} from '@/lib/checkout/packaging';
import {mergeIntegrationSection} from './integration-sections';
import {CheckoutError,address} from '@/lib/checkout/core';
export const secretNames=['paypalSandboxId','paypalSandboxSecret','paypalSandboxWebhook','paypalLiveId','paypalLiveSecret','paypalLiveWebhook','taxjarSandboxToken','taxjarLiveToken','shippoSandboxToken','shippoLiveToken'] as const;
function key(){const value=process.env.INTEGRATION_ENCRYPTION_KEY||'';if(!/^[a-f0-9]{64}$/i.test(value))throw new CheckoutError('Set INTEGRATION_ENCRYPTION_KEY to a dedicated 64-character hexadecimal key in Vercel before saving credentials.',503);return Buffer.from(value,'hex');}
function encrypt(value:string){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);const encrypted=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return [iv,cipher.getAuthTag(),encrypted].map(v=>v.toString('base64')).join('.');}
function decrypt(value:string){try{const [iv,tag,data]=value.split('.').map(v=>Buffer.from(v,'base64'));const decipher=createDecipheriv('aes-256-gcm',key(),iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(data),decipher.final()]).toString();}catch{throw new CheckoutError('Stored integration credentials cannot be unlocked. Check the encryption key.',503);}}
export async function storedIntegrations(){const {data,error}=await db().from('commerce_settings').select('value').eq('key','integrations').maybeSingle();if(error)throw error;return data?.value||null;}
export async function integrationConfig(){const stored=await storedIntegrations();const {data,error}=await db().from('commerce_settings').select('value').eq('key','checkout').single();if(error)throw error;return stored?.config||{paymentProvider:'paypal',paymentEnabled:data.value.enabled,paymentMode:data.value.paymentMode||'sandbox',taxEnabled:process.env.TAXJAR_ENABLED==='true',taxMode:process.env.TAXJAR_ENVIRONMENT||'sandbox',shippingEnabled:data.value.shippingEnabled,shippingMode:data.value.shippingMode||'sandbox',origin:data.value.origin,parcel:{length:12,width:9,height:4,emptyWeight:12,itemWeight:2,maxItems:24}};}
export async function credentials(){const stored=await storedIntegrations();const mode=process.env.PAYPAL_ENVIRONMENT==='live'?'Live':'Sandbox';const values:Record<string,string>={['paypal'+mode+'Id']:process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID||'',['paypal'+mode+'Secret']:process.env.PAYPAL_CLIENT_SECRET||'',['paypal'+mode+'Webhook']:process.env.PAYPAL_WEBHOOK_ID||'',taxjarSandboxToken:process.env.TAXJAR_SANDBOX_API_TOKEN||'',taxjarLiveToken:process.env.TAXJAR_LIVE_API_TOKEN||'',shippoSandboxToken:process.env.SHIPPO_TEST_API_TOKEN||'',shippoLiveToken:process.env.SHIPPO_LIVE_API_TOKEN||''};for(const name of secretNames)if(stored?.secrets?.[name])values[name]=decrypt(stored.secrets[name]);return values;}
export async function integrationSummary(){const config=await integrationConfig(),stored=await storedIntegrations();const envMode=process.env.PAYPAL_ENVIRONMENT==='live'?'Live':'Sandbox';const env:Record<string,boolean>={['paypal'+envMode+'Id']:!!process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID,['paypal'+envMode+'Secret']:!!process.env.PAYPAL_CLIENT_SECRET,['paypal'+envMode+'Webhook']:!!process.env.PAYPAL_WEBHOOK_ID,taxjarSandboxToken:!!process.env.TAXJAR_SANDBOX_API_TOKEN,taxjarLiveToken:!!process.env.TAXJAR_LIVE_API_TOKEN,shippoSandboxToken:!!process.env.SHIPPO_TEST_API_TOKEN,shippoLiveToken:!!process.env.SHIPPO_LIVE_API_TOKEN};const {data:products,error:productsError}=await db().from('commerce_products').select('product_type');if(productsError)throw productsError;return {config,productTypes:[...new Set((products||[]).map(p=>p.product_type))].sort(),encryptionReady:/^[a-f0-9]{64}$/i.test(process.env.INTEGRATION_ENCRYPTION_KEY||''),configured:Object.fromEntries(secretNames.map(k=>[k,stored?.secrets?.[k]?'Saved securely':env[k]?'Vercel environment':'Not configured']))};}
export async function saveIntegrations(input:any){const old=await storedIntegrations();const c=mergeIntegrationSection(await integrationConfig(),input);if(!c||!['paypal','none'].includes(c.paymentProvider)||!['sandbox','live'].includes(c.paymentMode)||!['sandbox','live'].includes(c.taxMode)||!['sandbox','live'].includes(c.shippingMode))throw new CheckoutError('Choose valid providers and modes.');if(c.paymentEnabled&&c.paymentProvider==='none')throw new CheckoutError('Choose a supported payment provider before enabling payments.');if(input.section==='Payment processing'&&c.paymentEnabled&&c.paymentMode==='live'&&input.confirmLive!==true)throw new CheckoutError('Confirm that you intend to accept real payments before saving live mode.');const parcel=validateParcel(c.parcel);const parcelProfiles:Record<string,ReturnType<typeof validateParcel>>={};if(c.parcelProfiles!==undefined&&(!c.parcelProfiles||typeof c.parcelProfiles!=='object'||Array.isArray(c.parcelProfiles)||Object.keys(c.parcelProfiles).length>100))throw new CheckoutError('Invalid shipping packing rules.');for(const [type,profile] of Object.entries(c.parcelProfiles||{})){if(!type.trim()||type.length>100||['__proto__','constructor','prototype'].includes(type))throw new CheckoutError('Invalid product type.');parcelProfiles[type]=validateParcel(profile);}
 const config={paymentProvider:c.paymentProvider,paymentEnabled:c.paymentEnabled===true,paymentMode:c.paymentMode,taxEnabled:c.taxEnabled===true,taxMode:c.taxMode,shippingEnabled:c.shippingEnabled===true,shippingMode:c.shippingMode,origin:address(c.origin),parcel,parcelProfiles};const secrets={...old?.secrets};for(const name of secretNames){const value=input.secrets?.[name];if(value!==undefined&&typeof value!=='string')throw new CheckoutError('Invalid credential.');if(value?.trim()&&!((input.section==='Payment processing'&&name.startsWith('paypal'))||(input.section==='Sales tax'&&name.startsWith('taxjar'))||(input.section==='Shipping'&&name.startsWith('shippo'))))throw new CheckoutError('Save credentials from their matching configuration section.');if(value?.trim()){if(value.length>4096)throw new CheckoutError('Credential is too long.');secrets[name]=encrypt(value.trim());}}
 const current=await credentials();for(const name of secretNames)if(input.secrets?.[name]?.trim())current[name]=input.secrets[name].trim();const suffix=(m:string)=>m==='live'?'Live':'Sandbox';if(config.paymentEnabled&&(!current['paypal'+suffix(c.paymentMode)+'Id']||!current['paypal'+suffix(c.paymentMode)+'Secret']||!current['paypal'+suffix(c.paymentMode)+'Webhook']))throw new CheckoutError('Client ID, client secret, and webhook ID are required for the selected payment mode.');if(config.taxEnabled&&!current['taxjar'+suffix(c.taxMode)+'Token'])throw new CheckoutError('Add the TaxJar token for the selected mode.');if(config.shippingEnabled&&!current['shippo'+suffix(c.shippingMode)+'Token'])throw new CheckoutError('Add the Shippo token for the selected mode.');if(config.paymentEnabled&&c.paymentMode==='live'&&((config.taxEnabled&&c.taxMode!=='live')||(config.shippingEnabled&&c.shippingMode!=='live')))throw new CheckoutError('Live payments require live enabled tax and shipping services.');if(old){const {data:updated,error}=await db().from('commerce_settings').update({value:{config,secrets}}).eq('key','integrations').eq('value',JSON.stringify(old)).select('key').maybeSingle();if(error)throw error;if(!updated)throw new CheckoutError('Configuration changed in another window. Reload and review the latest settings before saving.',409);}else{const {error}=await db().from('commerce_settings').insert({key:'integrations',value:{config,secrets}});if(error?.code==='23505')throw new CheckoutError('Configuration changed in another window. Reload before saving.',409);if(error)throw error;}
}
export async function paymentCredentials(mode:string){const values=await credentials(),suffix=mode==='live'?'Live':'Sandbox';return {id:values['paypal'+suffix+'Id'],secret:values['paypal'+suffix+'Secret'],webhook:values['paypal'+suffix+'Webhook']};}
