'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {DEFAULT_DELIVERY_EXPECTATIONS} from '@/lib/checkout/fulfillment-copy';
import {siteCopy,siteLine} from '@/lib/content/copy';
type Group={title:string;items:{id:string;title:string;detail:string;tabs:string[]}[]};
const groups:Group[]=[{title:'General',items:[{id:'general',title:'General',detail:'Product information and local delivery',tabs:['Product information','Local delivery']}]},{title:'Pages',items:[{id:'home',title:'Home',detail:'Hero, pink and gold lines, and Cookie of the Month',tabs:['Hero','Story','Closing','Cookie of the Month']},{id:'story',title:'My Story',detail:'The story page',tabs:['Story']},{id:'policies',title:'Policies',detail:'Cancellation and allergen notice',tabs:['Cancellation','Allergens']}]}];
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const prior=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{prior?.focus();};},[]);return <dialog ref={ref} className="content-modal" aria-labelledby="content-modal-title" onCancel={e=>{e.preventDefault();onClose();}}><header><h2 id="content-modal-title">{title}</h2><button type="button" aria-label="Close" onClick={onClose}>×</button></header><div className="content-modal-body">{children}</div></dialog>;}
export function ContentManager({site,products,busy,message,onChange,onSave}:{site:any;products:any[];busy:boolean;message:string;onChange:(key:string,value:unknown)=>void;onSave:()=>void}){
 const [open,setOpen]=useState<string|null>(null),[pane,setPane]=useState('');
 const item=groups.flatMap(g=>g.items).find(i=>i.id===open);
 function choose(id:string){const next=groups.flatMap(g=>g.items).find(i=>i.id===id);setOpen(id);setPane(next?.tabs[0]||'');}
 const field=(key:string,label:ReactNode,hint?:string)=><label key={key}>{label}<textarea rows={key==='storyBody'?12:3} maxLength={key==='storyBody'?10000:key==='deliveryExpectations'?2000:1500} value={site[key]??(key==='deliveryExpectations'?DEFAULT_DELIVERY_EXPECTATIONS:siteCopy[key as keyof typeof siteCopy]||'')} onChange={e=>onChange(key,e.target.value)}/>{hint&&<small>{hint}</small>}</label>;
 const accent=(key:keyof typeof siteCopy,label:string,tone:'pink'|'gold')=>field(key,<><span className={'accent-'+tone}>{tone==='pink'?'Pink text':'Gold text'}</span> · {label}</>,'Shown in the '+tone+' script on the homepage. Clearing it restores the current line.');
 return <><p>Choose General or a page. Each editor opens in a window.</p>{groups.map(group=><section key={group.title}><h2>{group.title}</h2><div className="admin-list">{group.items.map(entry=><button className="admin-list-row" key={entry.id} onClick={()=>choose(entry.id)}><span><strong>{entry.title}</strong><small>{entry.detail}</small></span><span>Edit →</span></button>)}</div></section>)}
 {item&&<Modal title={item.title} onClose={()=>setOpen(null)}>{item.tabs.length>1&&<div className="tabs" role="tablist" aria-label={item.title}>{item.tabs.map(tab=><button key={tab} type="button" aria-pressed={pane===tab} onClick={()=>setPane(tab)}>{tab}</button>)}</div>}
 {item.id==='general'&&pane==='Product information'&&<><p>Turning a section off hides it on every product. When on, each product controls its own visibility.</p>{[['showNutrition','Nutrition Facts & ingredient names'],['showAllergens','Potential allergens'],['showFreshness','Freshness information']].map(([key,label])=><label className="checkbox-label" key={key}><input type="checkbox" checked={site[key]!==false} onChange={e=>onChange(key,e.target.checked)}/>{label}</label>)}</>}
 {item.id==='general'&&pane==='Local delivery'&&<>{field('deliveryExpectations','Local delivery expectations','Shown on new local-delivery reviews, confirmations, and receipt emails. Earlier orders keep the wording from when they were placed. This does not apply to carrier shipping or pickup.')}</>}
 {item.id==='home'&&pane==='Hero'&&<>{field('heroPrefix','Headline','The pink word is added at the end. Use a new line where the headline should break.')}{accent('heroAccent','the word after the headline','pink')}{field('heroEyebrow','Line under the headline')}</>}
 {item.id==='home'&&pane==='Story'&&<>{accent('storyGreeting','greeting','gold')}{field('storyIntro','Introduction under the greeting')}</>}
 {item.id==='home'&&pane==='Closing'&&<>{accent('closingAccent','script line','pink')}{field('closingTitle','Line under the script')}</>}
 {item.id==='home'&&pane==='Cookie of the Month'&&<label>Cookie of the Month<select value={site.monthlyProductId||''} onChange={e=>onChange('monthlyProductId',e.target.value)}><option value="">Choose an active product</option>{products.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label>}
 {item.id==='story'&&field('storyBody','Full story')}
 {item.id==='policies'&&pane==='Cancellation'&&field('cancellationPolicy','Cancellation policy')}
 {item.id==='policies'&&pane==='Allergens'&&field('allergenNotice','Allergen notice')}
 {message&&<p role="status" className="message">{message}</p>}<button disabled={busy} onClick={onSave}>{busy?'Saving…':'Save'}</button><p className="content-preview">Preview: {siteLine(site.heroPrefix,siteCopy.heroPrefix).replace(/\n/g,' ')} <span className="accent-pink">{siteLine(site.heroAccent,siteCopy.heroAccent)}</span> · <span className="accent-gold">{siteLine(site.storyGreeting,siteCopy.storyGreeting)}</span> · <span className="accent-pink">{siteLine(site.closingAccent,siteCopy.closingAccent)}</span></p></Modal>}</>;
}
