'use client';
import StateSelect from '@/components/state-select';
import {useEffect,useState} from 'react';
export function CustomerDashboard(){const [data,setData]=useState<any>(null),[message,setMessage]=useState('');async function load(){const r=await fetch('/api/account',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function address(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const values=Object.fromEntries(new FormData(form));try{const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'address',address:{...values,country:'US'}})});const d=await r.json();if(!r.ok)throw new Error(d.error);form.reset();await load();setMessage('Address saved.');}catch(e){setMessage((e as Error).message);}}
 async function reorder(o:any){try{const r=await fetch('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({items:o.items.map((i:any)=>({id:i.id,quantity:i.quantity}))})});const d=await r.json();if(!r.ok)throw new Error(d.error);location.assign('/checkout');}catch(e){setMessage((e as Error).message);}}
 async function remove(id:string){const r=await fetch('/api/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'remove-address',id})});if(r.ok)load();else setMessage('Could not remove address.');}
 return <>{message&&<p role="status">{message}</p>}{data&&<>{data.isAdmin&&<p><a className="button" href="/admin">Manage the bakery</a></p>}<section className="account-orders"><h2>Your orders</h2>{!data.orders.length&&<p>Your confirmed orders will appear here.</p>}{data.orders.map((o:any)=><section className="card" key={o.id}><h3>{new Date(o.created_at).toLocaleDateString()} · {o.status}</h3><p>{o.id} · {o.mode==='sandbox'?'Sandbox test · ':''}${(o.total_cents/100).toFixed(2)}</p>{o.items.map((i:any)=><p key={i.id}>{i.quantity} × {i.title}</p>)}{!!o.donation_cents&&<p>CureSearch support: ${(o.donation_cents/100).toFixed(2)}</p>}<p>Subtotal ${((o.subtotal_cents||0)/100).toFixed(2)} · Shipping ${((o.shipping_cents||0)/100).toFixed(2)} · Tax ${((o.tax_cents||0)/100).toFixed(2)}</p><button onClick={()=>reorder(o)}>Reorder</button><p>Reordering replaces your bag; current prices and availability apply.</p></section>)}</section><section className="account-addresses"><h2>Saved addresses</h2>{data.addresses.map((a:any)=><p key={a.id}>{a.address.name} · {a.address.street1}, {a.address.city} <button onClick={()=>remove(a.id)}>Remove</button></p>)}<details className="account-address-form"><summary>Add a new address</summary><form onSubmit={address}>{['name','street1','street2','city','state','zip'].map(k=><label key={k}>{{name:'Name',street1:'Street address',street2:'Apartment / suite (optional)',city:'City',state:'State',zip:'ZIP code'}[k]}{k==='state'?<StateSelect name={k} required/>:<input name={k} required={k!=='street2'}/>}</label>)}<button>Save address</button></form></details></section><p className="account-next"><a href="/checkout">Continue to checkout</a> · <a href="/reviews">Leave a review</a></p></>}</>;
}
