'use client';
import {useEffect,useState} from 'react';
export function IntegrationSettings({section}:{section:'Payment processing'|'Sales tax'|'Shipping'}){const [data,setData]=useState<any>(null),[secrets,setSecrets]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[confirmLive,setConfirmLive]=useState(false);
 useEffect(()=>{fetch('/api/admin/integrations').then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);}).catch(e=>setMessage(e.message));},[]);
 function change(key:string,value:any){setData((d:any)=>({...d,config:{...d.config,[key]:value}}));setConfirmLive(false);}
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({config:data.config,secrets,confirmLive})});const d=await r.json();if(!r.ok)throw Error(d.error);setData(d);setSecrets({});setMessage('Configuration saved. New checkout quotes will use these settings.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const credential=(key:string,label:string)=><label key={key}>{label}<small> · {data.configured[key]}</small><input type="password" autoComplete="new-password" value={secrets[key]||''} placeholder="Leave blank to keep the existing value" onChange={e=>setSecrets({...secrets,[key]:e.target.value})}/></label>;
 const mode=(key:string)=><label>Environment<select value={data.config[key]} onChange={e=>change(key,e.target.value)}><option value="sandbox">Sandbox / test</option><option value="live">Production / live</option></select></label>;
 const toggle=(key:string,label:string)=><label className="checkbox-label"><input type="checkbox" checked={data.config[key]} onChange={e=>change(key,e.target.checked)}/>{label}</label>;
 return <section className="card integration-settings">{message&&<p role="status">{message}</p>}{!data?<p>Loading configuration…</p>:<><p>Credentials are server-only and never displayed after saving. Blank credential fields preserve existing values.</p>{!data.encryptionReady&&<p className="message">Credential entry needs the dedicated INTEGRATION_ENCRYPTION_KEY in Vercel. Existing environment credentials continue to work.</p>}
 {section==='Payment processing'&&<><label>Payment provider<select value={data.config.paymentProvider} onChange={e=>change('paymentProvider',e.target.value)}><option value="paypal">PayPal</option><option value="none">No payment provider</option></select></label><p>PayPal is currently the supported checkout adapter. Additional providers require their own checkout and webhook integration before they can be selected here.</p>{toggle('paymentEnabled','Enable online payments')}{mode('paymentMode')}{['Sandbox','Live'].map(m=><fieldset key={m}><legend>PayPal {m}</legend>{credential('paypal'+m+'Id','Client ID')}{credential('paypal'+m+'Secret','Client secret')}{credential('paypal'+m+'Webhook','Webhook ID')}</fieldset>)}<p>Webhook URL: <code>{typeof window!=='undefined'?window.location.origin:''}/api/paypal/webhook</code></p></>}
 {section==='Sales tax'&&<>{toggle('taxEnabled','Calculate and collect sales tax with TaxJar')}<p>When disabled or unconfigured, no tax is collected. Cookies & Chips is responsible for calculating and submitting any taxes owed. When enabled, a TaxJar failure stops checkout rather than silently removing tax.</p>{mode('taxMode')}{credential('taxjarSandboxToken','TaxJar sandbox API token')}{credential('taxjarLiveToken','TaxJar production API token')}</>}
 {section==='Shipping'&&<>{toggle('shippingEnabled','Enable shipping quotes through Shippo')}{mode('shippingMode')}{credential('shippoSandboxToken','Shippo test token')}{credential('shippoLiveToken','Shippo live token')}<h3>Ship-from address</h3>{['name','street1','street2','city','state','zip','country'].map(k=><label key={k}>{k}<input value={data.config.origin[k]||''} onChange={e=>change('origin',{...data.config.origin,[k]:e.target.value})}/></label>)}<h3>Estimated shipping box</h3><p>These starting estimates must be replaced with measured packed dimensions and weights. Each box contains up to the configured capacity. Rates cover human cookies; other product types remain pickup only.</p>{Object.entries({length:'Length (inches)',width:'Width (inches)',height:'Height (inches)',emptyWeight:'Empty box and packing weight (oz)',itemWeight:'Weight per cookie (oz)',maxItems:'Maximum cookies per box'}).map(([k,label])=><label key={k}>{label}<input type="number" min="0.01" step={k==='maxItems'?'1':'any'} value={data.config.parcel[k]} onChange={e=>change('parcel',{...data.config.parcel,[k]:Number(e.target.value)})}/></label>)}<p>Disabling Shippo removes shipping from checkout. Pickup settings are preserved. This configuration retrieves rates; it does not automatically purchase shipping labels.</p></>}
 {data.config.paymentEnabled&&data.config.paymentMode==='live'&&<label className="checkbox-label"><input type="checkbox" checked={confirmLive} onChange={e=>setConfirmLive(e.target.checked)}/>I intend to accept real payments using these production settings.</label>}<button disabled={busy||(data.config.paymentEnabled&&data.config.paymentMode==='live'&&!confirmLive)} onClick={save}>Save configuration</button></>}</section>;
}
