'use client';
import {useEffect,useState,useImperativeHandle,type Ref} from 'react';
import {allergens} from '@/lib/recipes/constants';
const empty={instructions:'',yieldCount:24,servingGrams:0,rows:[] as any[],confirmedAllergens:[] as string[],crossContact:'',reviewed:false};
export type RecipeEditorHandle={saveDraft:()=>Promise<void>;isDirty:()=>boolean};
export function RecipeEditor({productId,ref}:{productId:string;ref?:Ref<RecipeEditorHandle>}){const [recipe,setRecipe]=useState<any>(empty),[nutrition,setNutrition]=useState<any>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState<any[]>([]),[published,setPublished]=useState(false),[dirty,setDirty]=useState(false);
 useImperativeHandle(ref,()=>({saveDraft:async()=>{if(dirty)await save(false,true,true);},isDirty:()=>dirty}));
 useEffect(()=>{let active=true;fetch('/api/admin/recipes?id='+encodeURIComponent(productId)).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error);if(active&&d){setRecipe({...empty,...d.recipe});setNutrition(d.nutrition);setPublished(d.published);}}).catch(e=>setMessage(e.message));return()=>{active=false;};},[productId]);
 function change(patch:any){setDirty(true);setRecipe((r:any)=>({...r,...patch,reviewed:false}));setNutrition(null);setPublished(false);}
 function row(i:number,patch:any){change({rows:recipe.rows.map((r:any,n:number)=>i===n?{...r,...patch}:r)});}
 async function search(){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/recipes?q='+encodeURIComponent(query));const d=await r.json();if(!r.ok)throw Error(d.error);setResults(d.foods);if(!d.foods.length)setMessage('No matches. Try the brand and ingredient, or scan the supplier’s exact name.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function save(publish:boolean,draft=false,propagate=false){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/recipes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:productId,recipe,publish,draft})});const d=await r.json();if(!r.ok)throw Error(d.error);setDirty(false);setNutrition(d.nutrition);setPublished(d.published);setMessage(draft?'Private instructions and ingredient rows saved. Calculate nutrition when amounts and yield are ready.':publish?'Nutrition, ingredients, and allergens published.':'Recipe saved privately and USDA nutrition calculated. Any previously published nutrition remains unchanged until you publish this revision.');}catch(e){setMessage((e as Error).message);if(propagate)throw e;}finally{setBusy(false);}}
 return <section className="recipe-editor"><h3>Private recipe</h3><label>Written recipe instructions<textarea rows={8} value={recipe.instructions||''} onChange={e=>change({instructions:e.target.value})}/></label><p>Instructions are for your bakery only and never appear on the storefront.</p><h3>USDA ingredient list</h3><p>Save this recipe separately before closing the product editor. Recipe amounts stay private. Customers see the reviewed ingredient list, allergens, and estimated nutrition for one cookie.</p><label>Find an ingredient in USDA<input value={query} placeholder="Ghirardelli semi-sweet chocolate chips" onChange={e=>setQuery(e.target.value)}/></label><button type="button" disabled={busy||query.trim().length<2} onClick={search}>Search USDA</button><div className="usda-results">{results.map(f=><button type="button" key={f.fdcId} onClick={()=>{change({rows:[...recipe.rows,{fdcId:f.fdcId,name:f.description.slice(0,200),amount:0,unit:'g',gramsPerUnit:0}]});setResults([]);setQuery('');}}><strong>{f.description}</strong><small>{f.brand} · {f.dataType} · USDA #{f.fdcId}</small></button>)}</div>
 {recipe.rows.map((r:any,i:number)=><fieldset key={i}><legend>Ingredient {i+1} · USDA #{r.fdcId}</legend><label>Customer-facing ingredient name<input value={r.name} onChange={e=>row(i,{name:e.target.value})}/></label><div className="recipe-row"><label>Amount<input type="number" min="0.001" step="any" value={r.amount||''} onChange={e=>row(i,{amount:Number(e.target.value)})}/></label><label>Unit<select value={r.unit} onChange={e=>row(i,{unit:e.target.value})}>{['g','kg','oz','lb','cup','tbsp','tsp','each'].map(u=><option key={u}>{u}</option>)}</select></label></div>{!['g','kg','oz','lb'].includes(r.unit)&&<label>Grams per {r.unit} (from this ingredient’s package or measured weight)<input type="number" min="0.001" step="any" value={r.gramsPerUnit||''} onChange={e=>row(i,{gramsPerUnit:Number(e.target.value)})}/></label>}<button type="button" className="secondary" onClick={()=>change({rows:recipe.rows.filter((_:any,n:number)=>i!==n)})}>Remove ingredient</button></fieldset>)}
 <div className="recipe-row"><label>Finished cookies per batch<input type="number" min="1" value={recipe.yieldCount} onChange={e=>change({yieldCount:Number(e.target.value)})}/></label><label>Baked weight of one cookie (g)<input type="number" min="0.1" step="0.1" value={recipe.servingGrams||''} onChange={e=>change({servingGrams:Number(e.target.value)})}/></label></div><p>Volume measurements need an ingredient-specific gram conversion. We do not assume that a cup of flour weighs the same as a cup of chocolate chips.</p><h4>Additional confirmed allergens</h4>{allergens.map(a=><label className="checkbox-label" key={a}><input type="checkbox" checked={recipe.confirmedAllergens.includes(a)} onChange={e=>change({confirmedAllergens:e.target.checked?[...recipe.confirmedAllergens,a]:recipe.confirmedAllergens.filter((v:string)=>v!==a)})}/>{a}</label>)}<label>Cross-contact / supplier warnings<textarea value={recipe.crossContact} onChange={e=>change({crossContact:e.target.value})}/></label><button type="button" disabled={busy} onClick={()=>save(false,true)}>Save private recipe draft</button><button type="button" disabled={busy||!recipe.rows.length} onClick={()=>save(false)}>Save recipe & calculate USDA nutrition</button>
 {nutrition&&<div className="card"><h4>Nutrition estimate · 1 cookie ({nutrition.servingGrams} g)</h4><p><strong>Ingredients:</strong> {nutrition.ingredients}</p><p><strong>Contains / potential allergens:</strong> {nutrition.allergens||'No allergens detected automatically. Check every supplier label.'}</p><dl>{Object.entries(nutrition.values).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v===null?'Not available':String(v)}</dd></div>)}</dl>{nutrition.missing.length>0&&<p>Missing USDA values: {nutrition.missing.join(', ')}. These will be shown as unavailable, not zero.</p>}<label className="checkbox-label"><input type="checkbox" checked={recipe.reviewed} onChange={e=>setRecipe({...recipe,reviewed:e.target.checked})}/>I reviewed the USDA matches, amounts, yield, supplier ingredients, and allergen warnings.</label><button type="button" disabled={busy||!recipe.reviewed} onClick={()=>save(true)}>Publish product nutrition</button><p>{published?'Published on the product page.':'Private draft.'}</p></div>}{message&&<p role="status">{message}</p>}</section>;
}
