import {publicSite} from '@/lib/management/auth';
import {localDelivery} from '@/lib/checkout/delivery';
import {limit} from '@/lib/management/rate-limit';
import {body,settings,session,db,failure,supportSchemaReady} from '@/lib/checkout/server';
import {address,cart,email,text,priceCart,subtotal,CheckoutError} from '@/lib/checkout/core';
import {shippingRates,verifyRate,calculateTax} from '@/lib/checkout/providers';
import {serverClient} from '@/lib/supabase/server';
export async function POST(request:Request){try{const input=await body(request),s=await settings(),sessionHash=await session();await limit(request,'checkout-quote',60);const buyerEmail=email(input.email),name=text(input.name,1,100),items=cart(input.items);const {data,error}=await db().from('commerce_products').select('*').in('id',items.map(l=>l.id));if(error)throw error;let lines=priceCart(items,data||[]);let discountCode:string|null=null;if(input.discountCode){const code=text(input.discountCode,3,40).toUpperCase();const {data:discount,error:discountError}=await db().from('commerce_discounts').select('*').eq('code',code).eq('active',true).maybeSingle();if(discountError||!discount||subtotal(lines)<discount.minimum_cents)throw new CheckoutError('That discount is unavailable or the order minimum has not been reached.');lines=lines.map(l=>({...l,unit_cents:Math.round(l.unit_cents*(100-discount.percent)/100)}));discountCode=code;}if(subtotal(lines)>100000)throw new CheckoutError('Please contact us for orders over $1,000.');let method=input.method;if(!['pickup','shipping','delivery'].includes(method))throw new CheckoutError('Choose pickup or delivery.');if(method==='pickup'&&!s.pickupEnabled)throw new CheckoutError('Pickup is not available.');const destination=method==='pickup'?s.origin:address({...input.address,name});let rate;let delivery=null;
 if(method!=='pickup'){const site=await publicSite();delivery=site.deliveryGeocodingEnabled===true?await localDelivery(s.origin,destination):null;method=delivery?'delivery':'shipping';if(method==='shipping'&&!s.shippingEnabled)throw new CheckoutError('Paid shipping is not available for this address. Please choose pickup or contact us.');}
 if(method==='shipping'){if(!input.rateToken)return Response.json({rates:await shippingRates(s,lines,destination,sessionHash)});rate=await verifyRate(input.rateToken,s,lines,destination,sessionHash);}
 const supportReady=await supportSchemaReady();if(input.donation===true&&!supportReady)throw new CheckoutError('The support option is not available yet. Please reload checkout.',409);const donation=input.donation===true?100:0;const shipping=rate?.amount_cents||0,tax=await calculateTax(s,lines,destination,shipping);const client=await serverClient();const {data:{user}}=await client.auth.getUser();const record={session_hash:sessionHash,customer_id:user?.email_confirmed_at&&user.email?.toLowerCase()===buyerEmail?user.id:null,email:buyerEmail,customer_name:name,create_account:input.createAccount===true&&!user,mode:s.paymentMode,items:lines,fulfillment:{method,address:destination,...(delivery?{delivery}:{}),...(rate?{rate,mode:s.shippingMode}:{})},tax_details:{...tax.details,discountCode},...(supportReady?{donation_cents:donation}:{}),subtotal_cents:subtotal(lines),shipping_cents:shipping,tax_cents:tax.amount,total_cents:subtotal(lines)+shipping+tax.amount+donation};const {data:order,error:saveError}=await db().from('commerce_orders').insert(record).select('id,items,subtotal_cents,shipping_cents,tax_cents,total_cents,mode,expires_at,fulfillment'+(supportReady?',donation_cents':'')).single();if(saveError)throw saveError;return Response.json({order:{...(order as any),fulfillment:{method:(order as any).fulfillment.method}}});}catch(error){return failure(error);}}
